# Generated by Django 6.0.3 on 2026-04-01 23:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('date', models.DateTimeField()),
                ('location', models.CharField(blank=True, max_length=200, null=True)),
                ('duration_minutes', models.IntegerField(default=50)),
                ('related_course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planner.course')),
            ],
        ),
    ]
