# Generated by Django 6.0.3 on 2026-04-27 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0003_course_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
    ]
